apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-transaction
  labels:
    app: service-transaction
spec:
  replicas: 2
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: service-transaction
  template:
    metadata:
      labels:
        app: service-transaction
    spec:
      containers:
      - name: service-transaction
        image: registrydagl.azurecr.io/aforo255azuretransaction:__Build.BuildId__
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
      imagePullSecrets:
      - name: aforo.com
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-transaction
spec:
  type: LoadBalancer
  selector:
    app: service-transaction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
