version: '3.4'

services:
  aforo255.azure.security:
    image: ${DOCKER_REGISTRY-}aforo255azuresecurity:__Build.BuildId__
    build:
      context: .
      dockerfile: AFORO255.AZURE.Security/Dockerfile
    ports:
    - 9001:80     

  aforo255.azure.account:
    image: ${DOCKER_REGISTRY-}aforo255azureaccount:__Build.BuildId__
    build:
      context: .
      dockerfile: AFORO255.AZURE.Account/Dockerfile
    ports:
    - 9002:80   

  aforo255.azure.transaction:
    image: ${DOCKER_REGISTRY-}aforo255azuretransaction:__Build.BuildId__
    build:
      context: .
      dockerfile: AFORO255.AZURE.Transaction/Dockerfile
    ports:
    - 9003:80   

  aforo255.azure.report:
    image: ${DOCKER_REGISTRY-}aforo255azurereport:__Build.BuildId__
    build:
      context: .
      dockerfile: AFORO255.AZURE.Report/Dockerfile
    ports:
    - 9004:80   
